vich_uploader:
    db_driver: orm

    mappings:
        client_image:
            uri_prefix: /images/client
            upload_destination: '%kernel.project_dir%/public/images/client'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
