controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
op_security_logout:
    path: /logout
    methods: GET

authentication_token:
    path: /authentication_token
    methods: ['POST']